# Generated by Django 5.2.8 on 2025-11-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentregistration_class_applying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='class_applying',
            field=models.CharField(choices=[('creche', 'Creche'), ('kindergarten', 'Kindergarten'), ('nursery_1', 'Nursery 1'), ('nursery_2', 'Nursery 2'), ('primary_1', 'Primary 1'), ('primary_2', 'Primary 2'), ('primary_3', 'Primary 3'), ('primary_4', 'Primary 4'), ('primary_5', 'Primary 5'), ('primary_6', 'Primary 6'), ('jss_1', 'JSS 1'), ('jss_2', 'JSS 2'), ('jss_3', 'JSS 3'), ('sss_1', 'SSS 1'), ('sss_2', 'SSS 2'), ('sss_3', 'SSS 3')], max_length=20),
        ),
    ]
