# Generated by Django 5.2.8 on 2025-11-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentregistration_class_applying'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
