# Generated by Django 5.2.8 on 2025-12-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentregistration_parent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
