# Generated by Django 5.2.8 on 2025-12-03 01:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentregistration_parent_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='child_picture',
            field=models.ImageField(upload_to='student_registration/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
