# Generated by Django 5.2.8 on 2025-12-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentregistration_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='last_birthday_email_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
