# Generated by Django 5.2.8 on 2026-01-13 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_teacher_last_birthday_email_sent'),
        ('students', '0007_studentregistration_last_birthday_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='gender',
            field=models.CharField(choices=[('male', 'Boy'), ('female', 'Girl')], default='male', max_length=10),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text='e.g., Primary 1A, JSS 2B', max_length=100)),
                ('class_level', models.CharField(choices=[('creche', 'Creche'), ('kindergarten', 'Kindergarten'), ('nursery_1', 'Nursery 1'), ('nursery_2', 'Nursery 2'), ('primary_1', 'Primary 1'), ('primary_2', 'Primary 2'), ('primary_3', 'Primary 3'), ('primary_4', 'Primary 4'), ('primary_5', 'Primary 5'), ('primary_6', 'Primary 6'), ('jss_1', 'JSS 1'), ('jss_2', 'JSS 2'), ('jss_3', 'JSS 3'), ('sss_1', 'SSS 1'), ('sss_2', 'SSS 2'), ('sss_3', 'SSS 3')], help_text='Grade/Level of the class', max_length=20)),
                ('academic_year', models.CharField(help_text='e.g., 2024/2025', max_length=20)),
                ('max_capacity', models.IntegerField(default=30)),
                ('classroom_location', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_teacher', models.ForeignKey(blank=True, help_text='Main class teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_taught', to='staff.teacher')),
                ('subject_teachers', models.ManyToManyField(blank=True, help_text='Teachers who teach subjects in this class', related_name='classes_teaching', to='staff.teacher')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['class_level', 'class_name'],
                'unique_together': {('class_name', 'academic_year')},
            },
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='assigned_class',
            field=models.ForeignKey(blank=True, help_text='Class assigned after admission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.class'),
        ),
    ]
