# Generated by Django 5.2.8 on 2025-11-21 02:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cv', 'Curriculum Vitae (CV)'), ('cover_letter', 'Cover Letter'), ('application_letter', 'Application Letter'), ('certificate', 'Certificate'), ('recommendation', 'Recommendation Letter'), ('contract', 'Employment Contract'), ('other', 'Other Document')], max_length=30)),
                ('document_title', models.CharField(max_length=200)),
                ('document_file', models.FileField(upload_to='staff_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('description', models.TextField(blank=True)),
                ('folder_name', models.CharField(default='General', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('date_of_joining', models.DateField()),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('volunteer', 'Volunteer')], default='full_time', max_length=20)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('resigned', 'Resigned'), ('retired', 'Retired')], default='active', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, help_text='Job title', max_length=100)),
                ('subject_specialization', models.CharField(blank=True, max_length=200)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('teaching_experience_years', models.IntegerField(default=0)),
                ('highest_qualification', models.CharField(blank=True, choices=[('ssce', 'SSCE/WAEC/NECO'), ('ond', 'OND'), ('nce', 'NCE'), ('hnd', 'HND'), ('bsc', 'B.Sc/B.A/B.Ed'), ('pgde', 'PGDE'), ('msc', 'M.Sc/M.A/M.Ed'), ('phd', 'Ph.D'), ('other', 'Other')], max_length=20)),
                ('qualification_details', models.TextField(blank=True, help_text='Details of qualifications obtained')),
                ('certifications', models.TextField(blank=True, help_text='Professional certifications')),
                ('training_attended', models.TextField(blank=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('annual_leave_days', models.IntegerField(default=30)),
                ('sick_leave_days', models.IntegerField(default=14)),
                ('leave_days_taken', models.IntegerField(default=0)),
                ('leave_balance', models.IntegerField(default=30)),
                ('performance_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Out of 5.00', max_digits=3)),
                ('last_appraisal_date', models.DateField(blank=True, null=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('exit_reason', models.TextField(blank=True)),
                ('cv_file', models.FileField(blank=True, upload_to='staff_cv/')),
                ('appointment_letter', models.FileField(blank=True, upload_to='staff_letters/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher/Staff',
                'verbose_name_plural': 'Teachers/Staff',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='StaffFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['folder_name'],
                'unique_together': {('staff', 'folder_name')},
            },
        ),
    ]
