# Generated by Django 5.2.8 on 2025-11-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
