# Generated by Django 5.2.8 on 2025-12-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_teacher_date_of_birth_teacher_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
