# Generated by Django 5.2.8 on 2025-12-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_teacher_first_name_teacher_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='last_birthday_email_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
