# Generated by Django 5.2.8 on 2025-11-24 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feereminder',
            name='student_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentregistration'),
        ),
    ]
