# Generated by Django 5.2.8 on 2025-11-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_feereminder_student_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feereminder',
            name='reminder_type',
            field=models.CharField(choices=[('due_soon', 'Due Soon (7 days before)'), ('due_today', 'Due Today'), ('overdue', 'Overdue'), ('Pending', 'Pending')], max_length=20),
        ),
    ]
