# Generated by Django 5.2.8 on 2025-12-16 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_feereminder_reminder_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_email', models.EmailField(max_length=254)),
                ('school_phone', models.CharField(max_length=20)),
                ('school_address', models.TextField()),
                ('days_before_due_reminder', models.IntegerField(default=7)),
                ('enable_due_soon_reminder', models.BooleanField(default=True)),
                ('enable_due_today_reminder', models.BooleanField(default=True)),
                ('enable_overdue_reminder', models.BooleanField(default=True)),
                ('overdue_reminder_frequency_days', models.IntegerField(default=3)),
                ('due_soon_email_template', models.TextField(blank=True)),
                ('due_today_email_template', models.TextField(blank=True)),
                ('overdue_email_template', models.TextField(blank=True)),
                ('payment_receipt_template', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('class_name', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(blank=True, max_length=20)),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='student',
        ),
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('PARTIAL', 'Partially Paid')], default='UNPAID', max_length=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_type', models.CharField(default='Tuition Fee', max_length=100)),
                ('academic_term', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='fees.student')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fee_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feerecord')),
            ],
            options={
                'ordering': ['-notified_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('DUE_SOON', 'Due Soon'), ('DUE_TODAY', 'Due Today'), ('OVERDUE', 'Overdue')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('email_subject', models.CharField(max_length=200)),
                ('email_body', models.TextField()),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('fee_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='fees.feerecord')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.DeleteModel(
            name='FeeReminder',
        ),
        migrations.DeleteModel(
            name='StudentFee',
        ),
        migrations.AddIndex(
            model_name='reminderlog',
            index=models.Index(fields=['fee_record', 'reminder_type', 'sent_at'], name='fees_remind_fee_rec_cca4de_idx'),
        ),
        migrations.AddIndex(
            model_name='feerecord',
            index=models.Index(fields=['payment_status', 'due_date'], name='fees_feerec_payment_bec304_idx'),
        ),
    ]
