# Generated by Django 5.1.3 on 2026-04-23 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_schoolsettings_student_remove_studentfee_student_and_more'),
        ('students', '0008_studentregistration_gender_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.studentregistration'),
        ),
    ]
