# Generated by Django 5.2.8 on 2025-11-30 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='parent',
            field=models.ForeignKey(limit_choices_to={'parent_profile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'teacher_profile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='parent',
            field=models.ForeignKey(limit_choices_to={'parent_profile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'teacher_profile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_parents', to=settings.AUTH_USER_MODEL),
        ),
    ]
