# Generated by Django 5.2.8 on 2025-11-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_date_joined_user_student_user_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student',
            new_name='students',
        ),
    ]
