# Generated by Django 5.2.8 on 2025-11-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('emit_week', 'EMIT Week'), ('professional_day', 'Professional Day'), ('cultural_day', 'Cultural Day'), ('graduation', 'Graduation Ceremony'), ('sports_day', 'Sports Day'), ('inter_house', 'Inter-House Sports'), ('excursion', 'Excursion'), ('parents_day', 'Parents Day'), ('other', 'Other Event')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('academic_year', models.CharField(help_text='e.g., 2024/2025', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cover_image', models.ImageField(blank=True, upload_to='events/%Y/')),
                ('venue', models.CharField(max_length=200)),
                ('organizers', models.TextField(help_text='Names of organizing committee')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_gallery/%Y/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='schoolevents.schoolevent')),
            ],
            options={
                'verbose_name_plural': 'Event Galleries',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=200)),
                ('document_file', models.FileField(upload_to='event_documents/%Y/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='schoolevents.schoolevent')),
            ],
        ),
    ]
