# Generated by Django 5.2.8 on 2025-11-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolevents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolevent',
            name='event_type',
            field=models.CharField(choices=[('emit_week', 'EMIT Week'), ('professional_day', 'Professional Day'), ('cultural_day', 'Cultural Day'), ('graduation', 'Graduation Ceremony'), ('sports_day', 'Sports Day'), ('inter_house', 'Inter-House Sports'), ('excursion', 'Excursion'), ('parents_day', 'P.T.A Meeting'), ('fruit_week', 'Fruit Week'), ('other', 'Other Event')], max_length=30),
        ),
    ]
