# Generated by Django 5.2.8 on 2025-11-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=130)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('course_registration', models.BooleanField(default=False)),
            ],
        ),
    ]
