# Generated by Django 5.2.8 on 2025-11-25 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0002_studentregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('surname', models.CharField(help_text="Child's surname/last name", max_length=100)),
                ('first_name', models.CharField(help_text="Child's first name", max_length=100)),
                ('middle_name', models.CharField(blank=True, help_text="Child's middle name (optional)", max_length=100)),
                ('date_of_birth', models.DateField(help_text="Child's date of birth")),
                ('state_of_origin', models.CharField(choices=[('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwa_ibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross_river', 'Cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('fct', 'FCT Abuja'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'Kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara')], max_length=50)),
                ('address', models.TextField(help_text='Full residential address')),
                ('class_applying', models.CharField(choices=[('crèche', 'Crèche'), ('kindergarten', 'Kindergarten'), ('nursery_1', 'Nursery 1'), ('nursery_2', 'Nursery 2'), ('primary_1', 'Primary 1'), ('primary_2', 'Primary 2'), ('primary_3', 'Primary 3'), ('primary_4', 'Primary 4'), ('primary_5', 'Primary 5'), ('primary_6', 'Primary 6'), ('jss_1', 'JSS 1'), ('jss_2', 'JSS 2'), ('jss_3', 'JSS 3'), ('sss_1', 'SSS 1'), ('sss_2', 'SSS 2'), ('sss_3', 'SSS 3')], max_length=20)),
                ('child_picture', models.ImageField(help_text="Upload child's passport photograph (JPG, PNG)", upload_to='student_registration/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('medical_conditions', models.TextField(blank=True, help_text='Any medical conditions or allergies')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('admitted', 'Admitted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
