# Generated by Django 5.2.8 on 2025-11-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_studentregistration'),
    ]

    operations = [
        # No-op: StudentRegistration model has been consolidated into the `students` app.
    ]
