# Generated by Django 5.2.8 on 2025-11-27 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0004_delete_studentregistration'),
    ]

    operations = [
        # No-op: Model creation moved to `students` app.
    ]
