# Generated by Django 5.2.8 on 2025-11-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0005_studentregistration'),
    ]

    operations = [
        # No-op: The StudentRegistration model has been consolidated into
        # the `students` app. Removing it here would fail if the model
        # does not exist in the migration state. Keep this migration
        # empty so the migration history remains consistent.
    ]
