# Generated by Django 5.2.8 on 2025-11-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0006_delete_studentregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentRegistration',
        ),
    ]
