# Generated by Django 5.2.8 on 2025-11-21 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_to_children', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Legal Guardian'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandparent', 'Grandparent'), ('sibling', 'Sibling'), ('other', 'Other')], default='father', max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('employer_address', models.TextField(blank=True)),
                ('office_phone', models.CharField(blank=True, max_length=17)),
                ('monthly_income_range', models.CharField(blank=True, max_length=50)),
                ('spouse_name', models.CharField(blank=True, max_length=200)),
                ('spouse_phone', models.CharField(blank=True, max_length=17)),
                ('spouse_occupation', models.CharField(blank=True, max_length=200)),
                ('number_of_children', models.IntegerField(default=0)),
                ('number_of_children_in_school', models.IntegerField(default=0)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('is_pta_member', models.BooleanField(default=False, verbose_name='PTA Member')),
                ('pta_membership_date', models.DateField(blank=True, null=True)),
                ('pta_position', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about parent/guardian')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'ordering': ['user'],
            },
        ),
    ]
