# Generated by Django 5.2.8 on 2025-11-21 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='paystack', max_length=50)),
                ('paystack_reference', models.CharField(blank=True, max_length=200)),
                ('authorization_url', models.URLField(blank=True)),
                ('access_code', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('fee_items', models.JSONField(default=list, help_text='List of fee items being paid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentregistration')),
            ],
            options={
                'verbose_name': 'Online Payment',
                'verbose_name_plural': 'Online Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
